### ISSUE TITLE
implement channel for redpanda

### ISSUE THREAD

**Issue by subes** [invesdwin/invesdwin-context-integration#33]
claims to be faster than kafka: https://github.com/redpanda-data/redpanda

**Comment by acristea2323** [comment]
We can use [ComposeContainer](https://java.testcontainers.org/modules/docker_compose/) in testcontainers and give it a docker-compose file directly from the project test directory via:
`new File("src/test/java/"+<TESTCLASS>.class.getPackageName().replace(".", "/")+"/docker-compose.yaml")`

**Comment by subes** [comment]
POLL_TIMEOUT makes a difference?

**Comment by acristea2323** [comment]
# RedPanda Connect
_This work was done following the example at https://docs.redpanda.com/redpanda-connect/get-started/quickstarts/rpk/_

1. To start implementing RedPanda Connect, a docker.yaml file had to be created:
```
input:
  kafka_franz:
    seed_brokers: [ "localhost:9092" ]
    topics: [ "input_topic" ]
    consumer_group: "rp-connect-demo"

pipeline:
  processors:
    - bloblang: 'root = this'   # example transform: 'root.name = this.name.uppercase()'

output:
  kafka_franz:
    seed_brokers: [ "localhost:9092" ]
    topic: "output_topic"
```
2. After successfully creating the file, the following can be used to start Redpanda Connect with the YAML, sharing the host network (so localhost:9092 in the YAML correctly points to the host Kafka/Redpanda):
```
docker run --rm --network host \
  -v "$PWD/connect.yaml:/connect.yaml" \
  docker.redpanda.com/redpandadata/connect:latest run /connect.yaml

```

3. When RedPanda Connect has started, messages can be sent and received (through the host Kafka) by sending the message to input_topic and reading it from output_topic by the consumer thanks to RedPanda Connect :
```
echo "hello" | bin/kafka-console-producer.sh --topic input_topic --bootstrap-server localhost:9092
bin/kafka-console-consumer.sh --topic output_topic --from-beginning --bootstrap-server localhost:9092
```
**NOTE:** This test could have also been done like the Kafka Connect example where the contents could be read from files instead of the topics. This can be accomplished by editing the YAML file to contain:
output:
  file:
    path: ./output.txt
